"""Incremental SQLite-backed repository index."""

import hashlib
import json
from dataclasses import asdict
from datetime import UTC, datetime
from pathlib import Path

from sqlalchemy import delete, select
from sqlalchemy.orm import Session

from forge.core.contracts import IndexUpdate, RepositoryProfile
from forge.core.models import (
    CodeSymbol,
    ImportRecord,
    IndexedFile,
    RepositoryProfileRecord,
)
from forge.repository.files import DEFAULT_SCAN_POLICY, ScanPolicy, iter_safe_files
from forge.repository.profiler import RepositoryProfiler
from forge.repository.python_adapter import PythonLanguageAdapter


def profile_to_json(profile: RepositoryProfile) -> str:
    """Serialize a repository profile without implementation-specific encoders."""
    value = asdict(profile)
    value["root"] = str(profile.root)
    return json.dumps(value, sort_keys=True)


def profile_from_json(value: str) -> RepositoryProfile:
    """Deserialize a trusted profile generated by Forge."""
    data = json.loads(value)
    data["root"] = Path(data["root"])
    for field in (
        "languages",
        "frameworks",
        "package_managers",
        "test_frameworks",
        "lint_tools",
        "type_checkers",
        "build_commands",
        "test_commands",
        "source_directories",
        "test_directories",
        "entry_points",
        "ci_configuration",
    ):
        data[field] = tuple(data[field])
    return RepositoryProfile(**data)


class SqlRepositoryIndexer:
    """Update Python file, symbol, import, and profile records transactionally."""

    def __init__(self, session: Session, policy: ScanPolicy = DEFAULT_SCAN_POLICY) -> None:
        self.session = session
        self.policy = policy
        self.adapter = PythonLanguageAdapter()

    def update(self, repository_id: str, root: Path) -> IndexUpdate:
        """Reparse changed Python files and remove records for deleted files."""
        profile = RepositoryProfiler(self.policy).profile(root)
        record = self.session.get(RepositoryProfileRecord, repository_id)
        serialized = profile_to_json(profile)
        if record is None:
            self.session.add(
                RepositoryProfileRecord(repository_id=repository_id, profile_json=serialized)
            )
        else:
            record.profile_json = serialized
            record.updated_at = datetime.now(UTC)

        current = {
            item.path: item
            for item in self.session.scalars(
                select(IndexedFile).where(IndexedFile.repository_id == repository_id)
            )
        }
        candidates = {
            item.relative_path.as_posix(): item
            for item in iter_safe_files(profile.root, self.policy)
            if item.relative_path.suffix.lower() in self.adapter.extensions
        }
        deleted_paths = set(current) - set(candidates)
        for path in deleted_paths:
            self.session.delete(current[path])

        indexed = unchanged = errors = 0
        for path, safe_file in candidates.items():
            content = safe_file.read_bytes()
            digest = hashlib.sha256(content).hexdigest()
            existing = current.get(path)
            if existing is not None and existing.content_hash == digest:
                unchanged += 1
                errors += existing.parse_error is not None
                continue
            if existing is None:
                existing = IndexedFile(
                    repository_id=repository_id,
                    path=path,
                    content_hash=digest,
                    language=self.adapter.language,
                    size_bytes=len(content),
                )
                self.session.add(existing)
                self.session.flush()
            else:
                self.session.execute(delete(CodeSymbol).where(CodeSymbol.file_id == existing.id))
                self.session.execute(
                    delete(ImportRecord).where(ImportRecord.file_id == existing.id)
                )
                existing.content_hash = digest
                existing.size_bytes = len(content)
                existing.indexed_at = datetime.now(UTC)
            existing.parse_error = None
            try:
                extraction = self.adapter.extract(content.decode("utf-8"), path)
            except (SyntaxError, UnicodeDecodeError) as exc:
                existing.parse_error = f"{type(exc).__name__}: {exc}"
                errors += 1
            else:
                self.session.add_all(
                    CodeSymbol(file_id=existing.id, **asdict(symbol))
                    for symbol in extraction.symbols
                )
                self.session.add_all(
                    ImportRecord(file_id=existing.id, **asdict(item)) for item in extraction.imports
                )
            indexed += 1
        self.session.commit()
        return IndexUpdate(indexed, unchanged, len(deleted_paths), errors)

    def is_current(self, repository_id: str, root: Path) -> bool:
        """Return whether the live profile and Python files match the persisted index."""
        profile_record = self.session.get(RepositoryProfileRecord, repository_id)
        if profile_record is None:
            return False
        profile = RepositoryProfiler(self.policy).profile(root)
        if profile_to_json(profile) != profile_record.profile_json:
            return False
        indexed = {
            item.path: item.content_hash
            for item in self.session.scalars(
                select(IndexedFile).where(IndexedFile.repository_id == repository_id)
            )
        }
        candidates = {
            item.relative_path.as_posix(): item
            for item in iter_safe_files(profile.root, self.policy)
            if item.relative_path.suffix.lower() in self.adapter.extensions
        }
        if indexed.keys() != candidates.keys():
            return False
        return all(
            indexed[path] == hashlib.sha256(safe_file.read_bytes()).hexdigest()
            for path, safe_file in candidates.items()
        )
